"""
PR Formatter: Formats PR descriptions and bodies
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from common.types import ReviewIssue, AgentReview


def format_pr_body(issue: 'ReviewIssue', agent_review: 'AgentReview', 
                   file_path: str, reason: str) -> str:
    """Format PR description for auto-fix PR
    
    Args:
        issue: Review issue that was fixed
        agent_review: Agent review that found the issue
        file_path: Path to the file that was fixed
        reason: Reason why this was auto-fixed
        
    Returns:
        Formatted PR body text
    """
    
    severity_icon = {
        'CRITICAL': '🔴',
        'HIGH': '🟠',
        'MEDIUM': '🟡',
        'LOW': '🔵',
        'INFO': 'ℹ️'
    }.get(issue.severity.value, '⚪')
    
    body = f"""## 🤖 Auto-Fix: {issue.category}

**This is an automated fix generated by AI.**

### Issue Found
- **Agent:** {agent_review.agent_name}
- **Severity:** {severity_icon} {issue.severity.value}
- **File:** `{file_path}`
"""
    
    if issue.line_number:
        body += f"- **Line:** {issue.line_number}\n"
    
    body += f"\n### Description\n\n{issue.description}\n"
    
    if issue.suggestion:
        body += f"\n### Suggested Fix\n\n{issue.suggestion}\n"
    
    body += f"""

---

### How to Review

1. **👀 Check the code changes** - Verify the fix is correct and safe
2. **👤 Human approval required** - This PR will NOT auto-merge without explicit human approval
3. **👍 Approve the PR** - If the fix looks good, approve it for merging
4. **👎 React with thumbs down** - To immediately close this PR
5. **💬 Comment** - For questions or requested changes
6. **🏷️ Optional:** Add `merge-when-ready` label **only after human approval** if you want auto-merge

### Why This Was Auto-Fixed

{reason}

This fix was automatically generated because it falls into a safe category. However, **all auto-fixes require human review and approval** before merging for security and quality assurance.

---

*Generated by Auto-Fix Bot • Part of the AI Code Review System*
*Label: `auto-fix` `ai-generated` `{issue.severity.value.lower()}`*
*⚠️ **Security:** This PR requires human approval - it will not auto-merge.*
"""
    
    return body

